CREATE user root WITH PASSWORD 'root';

CREATE DATABASE user_db;
CREATE DATABASE book_db;
CREATE DATABASE issue_db;

GRANT ALL PRIVILEGES ON DATABASE user_db TO root;
GRANT ALL PRIVILEGES ON DATABASE book_db TO root;
GRANT ALL PRIVILEGES ON DATABASE issue_db TO root;
