-- CREATE user my_user WITH PASSWORD 'my_user';

CREATE DATABASE user_db;
CREATE DATABASE book_db;
CREATE DATABASE issue_db;

-- GRANT ALL PRIVILEGES ON DATABASE user_db TO my_user;
-- GRANT ALL PRIVILEGES ON DATABASE book_db TO my_user;
-- GRANT ALL PRIVILEGES ON DATABASE issue_db TO my_user;
