version: "3.8"
services:

  backend_user:
    build:
      context: user_project/.
      dockerfile: Dockerfile
    ports:
      - "1111:1111"
    restart: always
    depends_on:
      - db
    env_file:
      - user_project/.env

  backend_book:
    build:
      context: book_project/.
      dockerfile: Dockerfile
    ports:
      - "2222:2222"
    restart: always
    depends_on:
      - db
    env_file:
      - book_project/.env

  backend_issue:
    build:
      context: issue_project/.
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    restart: always
    depends_on:
      - db
    env_file:
      - issue_project/.env

  db:
    build:
      context: postgresql/.
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    image: nginx:1.21.6
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [ nginx-debug, '-g', 'daemon off;' ]
    links:
      - backend_user
      - backend_book
      - backend_issue
    ports:
      - "8880:8880"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - ./rabbitmq_data:/data
