version: "3.8"
services:
  backend_user:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user_server
    ports:
      - "1234:1234"
    restart: always
    depends_on:
      - db
    env_file:
      - .env
  backend_book:

  backend_issue:

  db:
    image: postgres:14
    container_name: postgres_hw_2
    ports:
        - "8080:8080"
    restart: always
    volumes:
      - ./volumes/db
    env_file:
      - .env
  nginx:
    image: nginx:1.21.6
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [ nginx-debug, '-g', 'daemon off;' ]
    links:
      - backend
    ports:
      - "8880:8880"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - "rabbitmq_data:/data"
