version: "3.8"
services:
  user_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    restart: always
    depends_on:
      - user_db
    env_file:
      - .env
  user_db:
    image: postgres:14
    restart: always
    volumes:
      - ./volumes/db
    env_file:
      - .env
