version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user_service
    ports:
      - "1234:1234"
    restart: always
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:14
    container_name: postgres_user
    ports:
        - "8080:8080"
    restart: always
    volumes:
      - ./volumes/db
    env_file:
      - .env
