name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the stack
      run: docker-compose build

    - name: Run tests users
      run: docker-compose run backend_user python -m py.test -v

    - name: Run tests books
      run: docker-compose run backend_book python -m py.test -v

    - name: Run tests issue
      run: docker-compose run backend_issue python -m py.test -v
