name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Copy env file
      run: |
        cp issue_project/ci.env issue_project/.env
        cp book_project/ci.env book_project/.env
        cp user_project/ci.env user_project/.env

    - name: Build the stack
      run: docker-compose build

    - name: Run tests users
      run: docker-compose run backend_user python -m pytest -v

    - name: Run tests books
      run: docker-compose run backend_book python -m py.test -v

    - name: Run tests issue
      run: docker-compose run backend_issue python -m py.test -v
